### ISSUE TITLE
DLL for unity 64bit

### ISSUE THREAD

**Issue by breemts** [Laremere/unityVRPN#1]
Hi,
we were not able to compile the dll for Unity 64bit, because there are some dependencies missing. Your dll works really great, so it would be very nice if you can compile a 64bit dll and upload it.
Thanks

**Comment by arviceblot** [comment]
Have you tried building and linking with VRPN? That should be all you need. I've built the 64bit dll before but I won't have access to any of the machines that I've built it on for about a week.

**Comment by breemts** [comment]
we tried linking the vrpn package, and now we have two projects in visual studio. But when we want to compile there is till something missing. We usually don't use c++, so we have no idea why its not working. We are not in a hurry, so it would be nice from you if you can upload it, when you have the time.
