### ISSUE TITLE
where is the vrpn_Analog.h

### ISSUE THREAD

**Issue by Jachon** [Laremere/unityVRPN#2]
hello, i can't build the project, please help me.  :(

**Comment by arviceblot** [comment]
Hello,

This project is no longer maintained, please see my fork at: https://github.com/arviceblot/unityVRPN

However if you want to continue using this version, you must build and link it with this project: https://github.com/vrpn/vrpn
which I have already dealt with in my fork.

**Comment by Jachon** [comment]
@arviceblot thanks :)
